"""add_must_change_password

Revision ID: 8fb53bddf4f8
Revises: b6c8a5ea7783
Create Date: 2026-06-14 13:10:02.746864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb53bddf4f8'
down_revision: Union[str, Sequence[str], None] = 'b6c8a5ea7783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
